config/routes.rb
Rails.application.routes.draw do
  resources :cats do  # /cats/3/cat_rental_requests
    resources :cat_rental_requests, only: [:index, :new], as: :rental
  end
  resources :cat_rental_requests, except: [:index], as: :rental
  get "cat_rental_requests/:id/approve" => "cat_rental_requests#approve", as: :approve
  get "cat_rental_requests/:id/deny" => "cat_rental_requests#deny", as: :deny
  resources :users
  resource :session, only: [:create, :new, :destroy]
  delete "session/log_out_all" => "sessions#log_out_all", as: :log_out_all
  delete "session/:id/log_out" => "sessions#log_out_remote", as: :log_out_remote
end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date
#  end_date   :date
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          default("0"), not null
#

class CatRentalRequest < ActiveRecord::Base
  validates_presence_of :cat_id, :start_date, :end_date, :user_id
  validates :status, inclusion: {in: ["PENDING", "DENIED", "APPROVED"]}
  validate :overlapping_approved_requests, on: [:create, :approve!, :save]
  belongs_to :cat
  belongs_to :user
  after_initialize :init

  def overlapping_requests
    CatRentalRequest.where("((start_date BETWEEN :start_date AND :end_date) OR (end_date BETWEEN :start_date AND :end_date)) AND id != :id",
                            :start_date => self.start_date,
                            :end_date => self.end_date,
                            :id => self.cat_id
                            )
  end

  def overlapping_approved_requests
    if overlapping_requests.where(status: "APPROVED").any?
      errors[:overlap] = "Sorry, #{self.cat.name} can't be booked for this time."
    end
  end

  def init
    self.status ||= "PENDING"
  end

  def approve!
    CatRentalRequest.transaction do
      self.update!(:status => 'APPROVED')
      self.overlapping_requests.where(status: "PENDING").each do |request|
        request.deny!
      end
    end
  end

  def deny!
    CatRentalRequest.transaction do
      self.update!(:status => "DENIED")
    end
  end

  def is_owner?(owner_id)
    self.cat.user_id == owner_id
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :is_owner?, only: [:approve, :deny]

  def index
    @cat_requests = Cat.find(params[:cat_id]).cat_rental_requests
    render :index
  end

  def create
    merged_params = rental_params.merge({user_id: current_user.id})
    @cat_rental = CatRentalRequest.new(merged_params)
    if @cat_rental.save
      redirect_to rental_url(@cat_rental)
    else
      flash[:create_error] = @cat_rental.errors.full_messages
      redirect_to new_rental_url
    end
  end

  def new
    @cat_rental = CatRentalRequest.new(cat_id: 0,
                                       start_date: Date.tomorrow,
                                       end_date: Date.tomorrow.tomorrow
                                       )

    @cat_id = params[:cat_id]
    render :new
  end

  def edit
    render :edit
  end

  def show
    @cat_rental = CatRentalRequest.find(params[:id])
    if @cat_rental
      redirect_to cat_url(@cat_rental.cat)
    else
      flash[:cat_not_found] = "Request not found"
      redirect_to cats_url
    end
  end

  def update

  end

  def destroy
  end

  def approve
    @request = CatRentalRequest.find(params[:id])
    @request.approve!
    redirect_to :back
  end

  def deny
    @request = CatRentalRequest.find(params[:id])
    @request.deny!
    redirect_to :back
  end

  private
    def rental_params
      params.require(:rental).permit(:cat_id, :start_date, :end_date)
    end

    def is_owner?
      request = CatRentalRequest.find(params[:id])
      if !request.is_owner?(current_user.id)
        redirect_to :back
      end
    end
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/views/cat_rental_requests/_form.html.erb
<form action="<%=url%>" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="<%= method_name %>" />
  <label> Cat
    <select name="rental[cat_id]">
      <option></option>
      <% Cat.all.each do |cat| %>
        <option value="<%= cat.id %>"
            <% if cat.id.to_i == @cat_id.to_i %>
              selected="selected"
            <% end %>
          ><%= cat.name %></option>
      <% end %>
    </select>
  </label><br><br>
  <label> Start Date
    <input type="date" name="rental[start_date]">
  </label>
  <label> End Date
    <input type="date" name="rental[end_date]">
  </label>
  <input type="submit" value="Submit">
</form>

app/views/cat_rental_requests/create.html.erb
<h1>CatRentalRequests#create</h1>
<p>Find me in app/views/cat_rental_requests/create.html.erb</p>

app/views/cat_rental_requests/destroy.html.erb
<h1>CatRentalRequests#destroy</h1>
<p>Find me in app/views/cat_rental_requests/destroy.html.erb</p>

app/views/cat_rental_requests/edit.html.erb
<h1>CatRentalRequests#edit</h1>
<p>Find me in app/views/cat_rental_requests/edit.html.erb</p>

app/views/cat_rental_requests/index.html.erb
<h1>CatRentalRequests#index</h1>
<p>Find me in app/views/cat_rental_requests/index.html.erb</p>

app/views/cat_rental_requests/new.html.erb
<h1>CatRentalRequests#new</h1>
<%= render partial: "form", locals: {cat_rental: @cat_rental, title: "Create", method_name: "POST", url: rental_index_url  } %>

app/views/cat_rental_requests/show.html.erb
<h1>CatRentalRequests#show</h1>

app/views/cat_rental_requests/update.html.erb
<h1>CatRentalRequests#update</h1>
<p>Find me in app/views/cat_rental_requests/update.html.erb</p>