config/routes.rb
Rails.application.routes.draw do
  resources :cats do  # /cats/3/cat_rental_requests
    resources :cat_rental_requests, only: [:index, :new], as: :rental
  end
  resources :cat_rental_requests, except: [:index], as: :rental
  get "cat_rental_requests/:id/approve" => "cat_rental_requests#approve", as: :approve
  get "cat_rental_requests/:id/deny" => "cat_rental_requests#deny", as: :deny
  resources :users
  resource :session, only: [:create, :new, :destroy]
  delete "session/log_out_all" => "sessions#log_out_all", as: :log_out_all
  delete "session/:id/log_out" => "sessions#log_out_remote", as: :log_out_remote
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date
#  color       :string
#  name        :string
#  sex         :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer          default("0"), not null
#

class Cat < ActiveRecord::Base
  COLORS = [:red, :blue, :green, :yellow, :pink, :purple].map(&:to_s)
  SEXES = ['M', 'F']
  validates_presence_of :birth_date, :color, :name, :sex
  validates :color, inclusion: {in: COLORS}
  validates :sex, inclusion: {in: SEXES}
  has_many(
    :cat_rental_requests, dependent: :destroy
  )
  belongs_to :user

  def age
    Time.now.year - birth_date.year
  end



end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :owns_cat?, only: [:edit, :update]

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def edit
    @cat = Cat.find(params[:id])

  end

  def create
    merged_params = cat_params.merge({user_id: current_user.id})
    @cat = Cat.new(merged_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash[:create_failed] = @cat.errors.full_messages
      redirect_to new_cat_url
    end
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      flash[:update_failed] = @cat.errors.full_messages
      redirect_to edit_cat_url
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    if @cat
      @cat.destroy
      render @cat
    else
      redirect_to cats_url
    end
  end

  private
    def cat_params
      params.require(:cat).permit(:name, :sex, :birth_date, :color, :description)
    end

    def owns_cat?
      @cat = Cat.find(params[:id])
      if current_user.id != @cat.user_id

        redirect_to cats_url
      end
    end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<form action="<%=url%>" method="post">
  <input type="hidden"
       name="authenticity_token"
       value="<%= form_authenticity_token %>">
  <% if cat && cat.persisted? %>
    <input type="hidden" name="_method" value="<%= method_name %>" />
  <% end %>
  <label> Name
    <input type="text" name="cat[name]" value="<%= cat ? cat.name : ""%>" >
  </label>
  <br>
  <label> Male
    <input type="radio" name="cat[sex]" value="M"
    <% if cat && cat.sex == 'M' %>
      checked
    <% end %>
    >
  </label>
  <br>
  <label> Female
    <input type="radio" name="cat[sex]" value="F"
    <% if cat && cat.sex == 'F' %>
      checked
    <% end %>
    >
  </label>
  <br>
  <label> Color
    <select name="cat[color]">
      <option selected="selected"></option>
      <% Cat::COLORS.each do |color| %>
        <option value="<%= color %>"
          <% if cat && cat.color == color %>
            selected
          <% end %>
          > <%= color %> </option>
      <% end %>
    </select>
  </label>
  <br>
  <label> Birthday
    <input type="date" name="cat[birth_date]">
  </label>
  <br>
  <label> Description
    <textarea name="cat[description]"><%= cat.description if cat %></textarea>
  </label>
  <br>
  <input type="submit" value="Submit">
</form>

app/views/cats/create.html.erb
<h1>Cats#create</h1>
<p>Find me in app/views/cats/create.html.erb</p>

app/views/cats/destroy.html.erb
<h1>Cats#destroy</h1>
<p>Find me in app/views/cats/destroy.html.erb</p>

app/views/cats/edit.html.erb
<h1>Cats#edit</h1>
<%= render partial: "form", locals: {url: cat_url(@cat), cat: @cat, title: 'Edit', method_name: 'PATCH'} %>

app/views/cats/index.html.erb
<h1>Cats#index</h1>
<ul>
  <% @cats.each do |cat| %>
  <li> <%= link_to cat.name, cat_url(cat) %> </li>
  <% end %>
</ul>

app/views/cats/new.html.erb
<h1>Cats#new</h1>

<%= render partial: "form", locals: {url: cats_url, cat: @cat, title: 'Create', method_name: 'POST'} %>

app/views/cats/show.html.erb
<h1>Cats#show</h1>
<table>
  <th><%= @cat.name %> </th>
  <% @cat.attributes.each do |attribute, value| %>
    <% next if attribute.to_s == 'name' %>
    <tr>
      <td><%= attribute %></td>
      <td><%= value %></td>
    </tr>
  <% end %>
</table>

<%= button_to "Make A New Request", new_cat_rental_url(@cat), :method => :get %>


<div>
  <label> Requested timeslots </label>
</div>
<table>
  <tr>
    <th> User_id </th>
    <th> Start Date </th>
    <th> End Date </th>
    <th> Status </th>
  </tr>
  <% @cat.cat_rental_requests.order(:start_date).each do |request| %>
    <tr>
      <td><%= request.user.user_name %></td>
      <td><%= request.start_date %></td>
      <td><%= request.end_date %></td>
      <td> <%= request.status %> </td>
      <% if request.is_owner?(current_user.id) && request.status == "PENDING" %>
          <td><%= button_to "Approve", approve_url(request), method: :get %>
          <td><%= button_to "Deny", deny_url(request), method: :get %>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/cats/update.html.erb
<h1>Cats#update</h1>
<p>Find me in app/views/cats/update.html.erb</p>